# Generated by Django 5.1.2 on 2024-10-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PresetsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('line_spacing', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('alt', models.FloatField()),
                ('mode', models.CharField(max_length=6)),
                ('liters_per_hectar', models.IntegerField()),
            ],
        ),
    ]
